# Generated by Django 4.1.7 on 2023-04-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='decriprtion',
            new_name='desription',
        ),
    ]
