# Generated by Django 4.1.7 on 2023-04-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_rename_desription_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='archive',
            new_name='archived',
        ),
    ]
