# Generated by Django 4.0.6 on 2023-05-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseshop', '0002_alter_house_options_alter_housetype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='текст записи')),
                ('is_published', models.BooleanField(default=False)),
                ('description', models.TextField(default='', verbose_name='описание')),
                ('published_at', models.DateTimeField(null=True, verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
    ]
