# Generated by Django 4.0.6 on 2023-05-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseshop', '0003_newsitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsItem',
        ),
    ]
