# Generated by Django 4.0.6 on 2023-05-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0003_profile_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='orders',
        ),
    ]
